name: Jenkins Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  security-scan:
    steps:
    - name: Setup Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.9.6'
    - name: Run Security Scan
      uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@v2
      with:
        java-cache: 'maven' # Optionally enable use of a build dependency cache. Specify 'maven' or 'gradle' as appropriate.
        # java-version: 21 # Optionally specify what version of Java to set up for the build, or remove to use a recent default.
